flask_blog/posts/forms/__init__.py
from .create_post_form import CreatePostForm

flask_blog/posts/forms/create_post_form.py
from flask_wtf.form import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class CreatePostForm(FlaskForm):
    """
    This is the form for users to create new posts
    """
    title = StringField(label="Title", validators=[DataRequired(), ])
    content = TextAreaField(label="Content", validators=[DataRequired(), ])

    submit = SubmitField(label="Post")

flask_blog/posts/__init__.py
from .views.delete_post import delete_post
from .views.edit_post import update_post
from .views.new_posts import new_post
from .views.post import post

flask_blog/posts/routes/__init__.py
from flask import Blueprint

posts = Blueprint("posts", __name__)

flask_blog/posts/routes/delete_post.py
from flask import flash, redirect, url_for, abort
from flask_login import login_required, current_user

from flask_blog import db
from flask_blog.models import Post
from flask_blog.posts.routes import posts


@posts.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash("Your post has been deleted!", category="success")
    return redirect(url_for("main.home"))

flask_blog/posts/routes/new_posts.py
from flask import render_template, redirect, url_for, flash
from flask_blog import db
from flask_blog.posts.forms.create_post_form import CreatePostForm

from flask_login import login_required, current_user

from flask_blog.models import Post
from flask_blog.posts.routes import posts


@posts.route("/post/new", methods=["GET", "POST"])
@login_required
def new_post():
    form = CreatePostForm()
    if form.validate_on_submit():
        post = Post(
            title=form.title.data,
            content=form.content.data,
            user_id=current_user.id
        )
        db.session.add(post)
        db.session.commit()
        flash(message="Your post has been created", category="success")
        return redirect(url_for("users.account"))
    return render_template("create_post.html", form=form, legend="Update Post")

flask_blog/posts/routes/post.py
from flask import render_template

from flask_blog.models import Post
from flask_blog.posts.routes import posts


@posts.route("/post/<int:post_id>", methods=["GET"])
def post(post_id):
    post_by_id = Post.query.get_or_404(post_id)
    return render_template("post.html", post=post_by_id)

flask_blog/posts/routes/update_post.py
from flask import flash, redirect, url_for, render_template, abort, request
from flask_login import login_required, current_user

from flask_blog import db
from flask_blog.posts.forms.create_post_form import CreatePostForm
from flask_blog.models import Post
from flask_blog.posts.routes import posts


@posts.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    form = CreatePostForm()

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data

        db.session.commit()
        flash(message="Your post has been updated", category="success")
        return redirect(url_for("post", post_id=post.id))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
    return render_template("update_post.html", form=form, legend="Update post")

flask_blog/posts/views/__init__.py
import os
from flask import Blueprint

BASE_DIR = os.path.dirname(os.path.dirname(__file__))

template_folder = os.path.join(BASE_DIR, "templates", "posts")

posts_blueprint = Blueprint("posts_blueprint", __name__, template_folder=template_folder)

flask_blog/posts/views/delete_post.py
from flask import flash, redirect, url_for, abort
from flask_login import login_required, current_user

from extensions import db
from flask_blog.models import Post
from flask_blog.posts.views import posts_blueprint


@posts_blueprint.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash("Your post has been deleted!", category="success")
    return redirect(url_for("public_blueprint.home"))

flask_blog/posts/views/edit_post.py
from flask import flash, redirect, url_for, render_template, abort, request
from flask_login import login_required, current_user

from extensions import db
from flask_blog.posts.forms.create_post_form import CreatePostForm
from flask_blog.models import Post
from flask_blog.posts.views import posts_blueprint


@posts_blueprint.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    form = CreatePostForm()

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data

        db.session.commit()
        flash(message="Your post has been updated", category="success")
        return redirect(url_for("posts_blueprint.post", post_id=post.id))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
    return render_template("update_post.html", form=form, legend="Update post")

flask_blog/posts/views/new_posts.py
from flask import render_template, redirect, url_for, flash

from extensions import db
from flask_blog.posts.forms.create_post_form import CreatePostForm

from flask_login import login_required, current_user

from flask_blog.models import Post
from flask_blog.posts.views import posts_blueprint


@posts_blueprint.route("/post/new", methods=["GET", "POST"])
@login_required
def new_post():
    form = CreatePostForm()
    if form.validate_on_submit():
        post = Post(
            title=form.title.data,
            content=form.content.data,
            user_id=current_user.id
        )
        db.session.add(post)
        db.session.commit()
        flash(message="Your post has been created", category="success")
        return redirect(url_for("users_blueprint.account"))
    return render_template("create_post.html", form=form, legend="Update Post")

flask_blog/posts/views/post.py
from flask import render_template

from flask_blog.models import Post
from flask_blog.posts.views import posts_blueprint


@posts_blueprint.route("/post/<int:post_id>", methods=["GET"])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template("post.html", post=post)

flask_blog/posts/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %} create post {% endblock title %}
{% block body %}

<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create Post</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                {{ form.title(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                {{ form.content(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock body %}

flask_blog/posts/templates/posts/post.html
{% extends "base.html" %}
{% block title %} home page {% endblock title %}
{% block body %}
<article class="media content-section">
    <img class="rounded-circle article-img"
         src='{{url_for("static", filename="images/"+post.author.image_file)}}'>
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{url_for('users_blueprint.account')}}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime("%Y-%m-%d") }}</small>
        </div>
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
        {% if post.author == current_user %}
        <div>
            <a class="btn btn-secondary btn-sm m-1"
               href="{{url_for('posts_blueprint.update_post',post_id=post.id)}}">Edit post</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal"
                    data-target="#deleteModal">Delete</button>
        </div>
        {% endif %}
    </div>
</article>
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog"
     aria-labelledby="deleteModalLabel"
     aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete post `{{post.title}}`?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to <strong>DELETE</strong>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="{{url_for('posts_blueprint.delete_post', post_id=post.id)}}" method="POST">
            <input type="submit" class="btn btn-danger" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock body %}

flask_blog/posts/templates/posts/update_post.html
{% extends "base.html" %}
{% block title %} update post {% endblock title %}
{% block body %}

<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{legend}}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                {{ form.title(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                {{ form.content(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock body %}